global:
  scrape_interval: 15s
scrape_configs:
  - job_name: searchforge-api
    static_configs:
      - targets: ["api:4000"]
  - job_name: searchforge-crawler
    static_configs:
      - targets: ["crawler:4010"]
  - job_name: searchforge-indexer
    static_configs:
      - targets: ["indexer:4020"]
  - job_name: searchforge-worker
    static_configs:
      - targets: ["worker:4030"]
